name        = "Sample Dataset"
description = "A sample app for the AnySet Framework"

path_prefix = "sample"
version     = 1

adapter = "PostgreSQL"

[adapter_config]
host     = "localhost"
port     = 5432
database = "mydatabase"
user     = "myuser"
password = "$env!PG_SAMPLE_DATASET_PASSWORD"

[custom_aggregation_functions]
# SUM_OF_TRANSACTION_AMOUNT = """
# SELECT SUM(TRANSACTION_AMOUNT) FROM cc_transactions
# """

[dataset_tables.cc_transactions]
name = "cc_transactions"

[dataset_tables.cc_transactions.columns.trans_num]
name             = "trans_num"
column_type      = "Other"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.trans_date_trans_time]
name             = "trans_date_trans_time"
column_type      = "DateTime"
column_data_type = "DateTime"

[dataset_tables.cc_transactions.columns.unix_time]
name             = "unix_time"
column_type      = "Other"
column_data_type = "Number"

[dataset_tables.cc_transactions.columns.is_fraud]
name             = "is_fraud"
column_type      = "Category"
column_data_type = "Boolean"

[dataset_tables.cc_transactions.columns.cc_num]
name             = "cc_num"
column_type      = "Other"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.merchant]
name             = "merchant"
column_type      = "Other"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.merch_zipcode]
name             = "merch_zipcode"
column_type      = "Other"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.merchant_lat]
name             = "merchant_lat"
column_type      = "Other"
column_data_type = "Number"

[dataset_tables.cc_transactions.columns.merchant_long]
name             = "merchant_long"
column_type      = "Other"
column_data_type = "Number"

[dataset_tables.cc_transactions.columns.category]
name             = "category"
column_type      = "Category"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.amt]
name             = "amt"
column_type      = "Fact"
column_data_type = "Number"

[dataset_tables.cc_transactions.columns.first]
name             = "first"
column_type      = "Other"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.last]
name             = "last"
column_type      = "Other"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.gender]
name             = "gender"
column_type      = "Category"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.street]
name             = "street"
column_type      = "Other"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.city]
name             = "city"
column_type      = "Other"
column_data_type = "String"
parent           = "state"

[dataset_tables.cc_transactions.columns.state]
name             = "state"
column_type      = "Category"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.zip]
name             = "zip"
column_type      = "Other"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.lat]
name             = "lat"
column_type      = "Other"
column_data_type = "Number"

[dataset_tables.cc_transactions.columns.long]
name             = "long"
column_type      = "Other"
column_data_type = "Number"

[dataset_tables.cc_transactions.columns.city_pop]
name             = "city_pop"
column_type      = "Other"
column_data_type = "Number"

[dataset_tables.cc_transactions.columns.job]
name             = "job"
column_type      = "Category"
column_data_type = "String"

[dataset_tables.cc_transactions.columns.dob]
name             = "dob"
column_type      = "DateTime"
column_data_type = "DateTime"
