[project]
name = "api"
version = "0.1.0"
description = "FastAPI backend for microfrontend application"
authors = []

requires-python = ">=3.12"

dependencies = [
    "fastapi==0.115.11",
    "uvicorn==0.34.0",
]

[tool.rye]
managed = true
dev-dependencies = []
